### PR TITLE
add ability to add twig extensions via configuration

### PR DESCRIPTION
**Pull request by robertfausk**
including documentation

### CODE REVIEW

**Comment by robertfausk** [comment]
@r1pp3rj4ck will there be any progress on this?

**Comment by attilabukor** [comment]
Sorry, I completely forgot about this. Wouldn't it be better to register the same extensions as in the "real" Twig? I mean with the same `twig.extension` tag instead of `twig2`.

**Comment by robertfausk** [comment]
I think it depends on the use case.

In my use case I need to render twig templates coming from database. There I use extensions which are not used in the "real" twig. With the given PR you can decide which Extensions will be available/loaded for different twig.

```
    twig2.extension.acme_render_cms:
        class: Acme\CmsBundle\Twig\CmsRenderExtension
        arguments:
            - @acme_repository
            - @router
        tags: [{ name: twig.extension }] # use extension for twig only 
```

```
    twig2.extension.acme_render_cms:
        class: Acme\CmsBundle\Twig\CmsRenderExtension
        arguments:
            - @acme_repository
            - @router
        tags: [{ name: twig2.extension }] # use extension for twig2 only 
```

```
    twig2.extension.acme_render_cms:
        class: Acme\CmsBundle\Twig\CmsRenderExtension
        arguments:
            - @acme_repository
            - @router
        tags: [{ name: twig.extension }, { name: twig2.extension }] # use extension for both twig and twig2
```

**Comment by attilabukor** [comment]
What if we subscribe to the `twig.extension` tag and create a new `twigstring.extension` tag? It would be more practical.

**Comment by robertfausk** [comment]
:+1:  for renaming `twig2` to `twigstring`

I'm not sure about performance issues if all extensions registered for `twig` will be also loaded for `twigstring` or am I mislead now?

**Comment by attilabukor** [comment]
Not sure about this, but it shouldn't cause any significant overhead.

**Comment by fadoe** [comment]
@r1pp3rj4ck What's the status of this PR?

**Comment by attilabukor** [comment]
@robertfausk could you please rename `twig2` to `twigstring` then?

**Comment by fadoe** [comment]
@r1pp3rj4ck What is the status of this PR? Will it be merged?

**Pull request closed without merging**
